=== N333N444/Overheid/pizza-deliveries/pizza-deliveries2 - schema with type reuse/deliveries2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/deliveries2" xmlns:tns="http://www.example.org/deliveries2" elementFormDefault="qualified">

	<xs:element name="deliveries">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="delivery" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- 
							  The following adds an attribute "price" to the string-typed element.
							  This is quite complicated for such a simple addition. 
							-->
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="price" type="xs:float"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="seller" type="tns:addressType" />
							<xs:element name="buyer" type="tns:addressType" />
						</xs:sequence>
						<xs:attribute name="time" type="xs:dateTime" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element> 

	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="street" type="xs:string" />
			<xs:element name="extra" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="zip" type="xs:string" />
			<xs:element name="city" type="xs:string" />
			<xs:element name="country" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== N333N444/Overheid/pizza-deliveries/pizza-deliveries2 - schema with type reuse/deliveries2.xml
<?xml version="1.0" encoding="UTF-8"?>
<deliveries xmlns="http://www.example.org/deliveries2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/deliveries2 deliveries2.xsd ">

  <delivery time="2021-03-11T19:25:00">
    <item price="12.50">Pizza</item>
    <seller>
      <name>De Pizzabakkers</name>
      <street>Nachtegaalstraat 70</street>
      <zip>3581 AM</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </seller>
    <buyer>
      <name>Peter Smith</name>
      <street>Parkstraat 31</street>
      <zip>3581 PC</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </buyer>
  </delivery>
  
  <delivery time="2021-03-11T19:54:10">
    <item price="11.30">Pizza</item>
    <item price="9.55">Pasta</item>
    <seller>
      <name>Vapiano</name>
      <street>Stationsplein 4</street>
      <zip>3511 ED</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </seller>
    <buyer>
      <name>Tom Snyder</name>
      <street>Princetonplein 5</street>
      <zip>3584 CC</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </buyer>
  </delivery>
  
  <delivery time="2021-03-11T20:17:52">
    <item price="7.80">Salad</item>
    <seller>
      <name>Vapiano</name>
      <street>Stationsplein 4</street>
      <zip>3511 ED</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </seller>
    <buyer>
      <name>Susi Miller</name>
      <street>Voorstraat 11</street>
      <zip>3512 AN</zip>
      <city>Utrecht</city>
      <country>NL</country>
    </buyer>
  </delivery>
  
</deliveries>
