=== N333N444/Overheid/pizza-deliveries/pizza-deliveries4 - schema with import and address transformation/PostalAddress-1_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Original source http://xml.coverpages.org/HR-XML-PostalAddress-1_2.pdf (modified) -->
<xsd:schema
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
	targetNamespace="http://xml.coverpages.org/HR-XML-PostalAddress-1_2"
	xmlns:tns="http://xml.coverpages.org/HR-XML-PostalAddress-1_2"
	elementFormDefault="qualified">
	<xsd:complexType name="PostalAddressType">
		<xsd:sequence>
			<xsd:element name="CountryCode">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[A-Z]{2}" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="PostalCode" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="Region" type="xsd:string"
				minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="Municipality" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="DeliveryAddress" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="AddressLine" type="xsd:string"
							minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="StreetName" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="BuildingNumber" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="Unit" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="PostOfficeBox" type="xsd:string"
							minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="Recipient" minOccurs="0"
				maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="FirstName" type="xsd:string" minOccurs="0" />
						<xsd:element name="MiddleName" type="xsd:string" minOccurs="0" />
						<xsd:element name="LastName" type="xsd:string" minOccurs="0" />
						<xsd:element name="AdditionalText" type="xsd:string"
							minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="Organization" type="xsd:string"
							minOccurs="0" />
						<xsd:element name="OrganizationName" type="xsd:string"
							minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="type" default="undefined">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="postOfficeBoxAddress" />
					<xsd:enumeration value="streetAddress" />
					<xsd:enumeration value="militaryAddress" />
					<xsd:enumeration value="undefined" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	
	<xsd:element name="PostalAddressList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="PostalAddress" type="tns:PostalAddressType" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== N333N444/Overheid/pizza-deliveries/pizza-deliveries4 - schema with import and address transformation/PostalAddress.xml
<adr:PostalAddressList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xmlns:del="http://www.example.org/deliveries4"
                       xmlns:adr="http://xml.coverpages.org/HR-XML-PostalAddress-1_2"
                       xsi:schemaLocation="http://xml.coverpages.org/HR-XML-PostalAddress-1_2 PostalAddress-1_2.xsd">
   <adr:PostalAddress type="streetAddress">
      <adr:CountryCode>NL</adr:CountryCode>
      <adr:PostalCode>3511 ED</adr:PostalCode>
      <adr:Municipality>Utrecht</adr:Municipality>
      <adr:DeliveryAddress>
         <adr:StreetName>Stationsplein</adr:StreetName>
         <adr:BuildingNumber>4</adr:BuildingNumber>
      </adr:DeliveryAddress>
   </adr:PostalAddress>
   <adr:PostalAddress type="streetAddress">
      <adr:CountryCode>NL</adr:CountryCode>
      <adr:PostalCode>3581 AM</adr:PostalCode>
      <adr:Municipality>Utrecht</adr:Municipality>
      <adr:DeliveryAddress>
         <adr:StreetName>Nachtegaalstraat</adr:StreetName>
         <adr:BuildingNumber>70</adr:BuildingNumber>
      </adr:DeliveryAddress>
   </adr:PostalAddress>
   <adr:PostalAddress type="streetAddress">
      <adr:CountryCode>NL</adr:CountryCode>
      <adr:PostalCode>3581 PC</adr:PostalCode>
      <adr:Municipality>Utrecht</adr:Municipality>
      <adr:DeliveryAddress>
         <adr:StreetName>Parkstraat</adr:StreetName>
         <adr:BuildingNumber>88</adr:BuildingNumber>
      </adr:DeliveryAddress>
   </adr:PostalAddress>
   <adr:PostalAddress type="streetAddress">
      <adr:CountryCode>NL</adr:CountryCode>
      <adr:PostalCode>3584 CC</adr:PostalCode>
      <adr:Municipality>Utrecht</adr:Municipality>
      <adr:DeliveryAddress>
         <adr:StreetName>Princetonplein</adr:StreetName>
         <adr:BuildingNumber>5</adr:BuildingNumber>
      </adr:DeliveryAddress>
   </adr:PostalAddress>
   <adr:PostalAddress type="streetAddress">
      <adr:CountryCode>NL</adr:CountryCode>
      <adr:PostalCode>3584 CC</adr:PostalCode>
      <adr:Municipality>Utrecht</adr:Municipality>
      <adr:DeliveryAddress>
         <adr:StreetName>Princetonplein</adr:StreetName>
         <adr:BuildingNumber>5</adr:BuildingNumber>
      </adr:DeliveryAddress>
   </adr:PostalAddress>
</adr:PostalAddressList>
